
import os
import time
import random
import json
import sys
from dotenv import load_dotenv
from core import GeminiBehaviorAnalyzer

# Load environment variables
load_dotenv()

# Set up safe printing for Windows consoles
sys.stdout.reconfigure(encoding='utf-8')

def safe_print(text):
    """Print safely handling unicode errors"""
    try:
        print(text)
    except UnicodeEncodeError:
        # Fallback to ascii
        print(text.encode('ascii', 'ignore').decode('ascii'))

def main():
    safe_print("=" * 60)
    safe_print("🛡️  GEMINI BEHAVIOR ANALYZER TEST - KEYSTROKE DYNAMICS")
    safe_print("=" * 60)

    api_key = os.getenv('GEMINI_API_KEY')
    if not api_key:
        safe_print("❌ Error: GEMINI_API_KEY not found in .env")
        return

    # Initialize the analyzer
    safe_print("\n⚙️  Initializing Gemini Behavior Analyzer (gemini-2.5-flash)...")
    try:
        analyzer = GeminiBehaviorAnalyzer(api_key, model_name='gemini-2.5-flash')
    except Exception as e:
        safe_print(f"❌ Initialization failed: {e}")
        return
    
    # --- SCENARIO 1: HUMAN TYPING SIMULATION ---
    safe_print("\n👤 SCENARIO 1: Simulating HUMAN Typing...")
    # Humans vary: 50ms to 300ms usually, with occasional pauses
    human_timings = []
    for _ in range(50):
        delay = random.randint(80, 250)
        # Add random "thinking" pauses
        if random.random() < 0.1: 
            delay += random.randint(300, 800)
        human_timings.append(delay)
    
    safe_print(f"   Generated {len(human_timings)} keystroke intervals (simulated human)")
    safe_print("   Analyzing with Gemini AI...")
    
    try:
        human_result = analyzer.analyze_keystroke_pattern(human_timings)
        safe_print("   ✅ Analysis Complete: Human detected" if human_result.get('is_human') else "   ⚠️ Unexpected Result")
    except Exception as e:
        safe_print(f"   ❌ Analysis failed: {e}")
        human_result = {"error": str(e)}
    
    
    # --- SCENARIO 2: BOT TYPING SIMULATION ---
    safe_print("\n🤖 SCENARIO 2: Simulating BOT/SCRIPT Typing...")
    # Bots are perfect: 5ms or 10ms constantly
    bot_timings = [10] * 50
    # Add tiny artificial noise (bots trying to hide)
    bot_timings = [t + random.randint(0, 2) for t in bot_timings]
    
    safe_print(f"   Generated {len(bot_timings)} keystroke intervals (simulated bot)")
    safe_print("   Analyzing with Gemini AI...")
    
    try:
        bot_result = analyzer.analyze_keystroke_pattern(bot_timings)
        safe_print("   ✅ Analysis Complete: Bot detected" if not bot_result.get('is_human') else "   ⚠️ Unexpected Result")
    except Exception as e:
        safe_print(f"   ❌ Analysis failed: {e}")
        bot_result = {"error": str(e)}
    
    # --- GENERATE REPORT ---
    safe_print("\n📝 Generating Forensic Report...")
    
    report_content = f"""# 🧠 Gemini Behavioral Analysis Report
**Generated**: {time.strftime('%Y-%m-%d %H:%M:%S')}
**Model Used**: {analyzer.model_name}
**Test Status**: COMPLETED

---

## 📋 Executive Summary
This report details the results of a behavioral biometrics test using Gemini AI to distinguish between human keystroke dynamics and automated script execution.

### 📊 Results Overview
| Scenario | Expected | AI Prediction | Confidence |
|----------|----------|---------------|------------|
| **Scenario 1** | Human | **{'Human' if human_result.get('is_human') else 'Bot'}** | {human_result.get('confidence', 0):.1%} |
| **Scenario 2** | Bot | **{'Bot' if not bot_result.get('is_human') else 'Human'}** | {bot_result.get('confidence', 0):.1%} |

---

## 👤 Scenario 1: Human Simulation
**Methodology**: Generated 50 keystrokes with random intervals (80-250ms) and occasional "thinking pauses" (300-800ms).

### Input Data Sample (first 10 intervals)
`{human_timings[:10]}...`

### 🧠 Gemini AI Analysis
> **Verdict**: {human_result.get('explanation', 'N/A')}

#### Full JSON Output
```json
{json.dumps(human_result, indent=2)}
```

---

## 🤖 Scenario 2: Bot Simulation
**Methodology**: Generated 50 keystrokes with constant intervals (10ms) and minimal jitter (0-2ms).

### Input Data Sample (first 10 intervals)
`{bot_timings[:10]}...`

### 🧠 Gemini AI Analysis
> **Verdict**: {bot_result.get('explanation', 'N/A')}

#### Full JSON Output
```json
{json.dumps(bot_result, indent=2)}
```

---
*Report generated by ShadowNet Nexus Behavioral Analysis Module*
"""
    
    report_file = "BEHAVIOR_ANALYSIS_REPORT.md"
    try:
        with open(report_file, "w", encoding='utf-8') as f:
            f.write(report_content)
        safe_print(f"✅ Report successfully saved to: {os.path.abspath(report_file)}")
    except Exception as e:
        safe_print(f"❌ Failed to save report: {e}")

if __name__ == "__main__":
    main()
